#!/usr/bin/env python3
"""Final build: v1 + new covers + new dividers, preserving form fields correctly.
Uses clone_document_from_reader + merge/delete so widget references stay intact."""
import os
from pypdf import PdfReader, PdfWriter
from PIL import Image

BASE = os.path.dirname(os.path.abspath(__file__))
COVERS = os.path.join(BASE, "covers")

# (v1 pdf, cover_key, {page: divider_template})
JOBS = [
    ("The_Whole_Vibe_Mind_Body_Soul_Wellness_Journal_v1.pdf", "wellness",
     {9: "wellness", 31: "wellness", 41: "wellness", 53: "wellness",
      67: "wellness", 79: "wellness", 97: "wellness", 105: "wellness"}),
    ("Faith_Vibe_Life_and_Bible_Companion_v1.pdf", "faith",
     {9: "faith", 17: "faith", 24: "faith", 30: "faith", 64: "faith",
      79: "faith", 90: "faith", 99: "faith", 109: "faith", 118: "faith"}),
    ("Healing_Vibe_Inner_Child_Boundaries_Self_Trust_Journal_v1.pdf", "healing",
     {12: "healing", 24: "healing", 36: "healing", 48: "healing",
      60: "healing", 73: "healing", 88: "healing", 111: "healing"}),
    ("Faith_Vibe_Ethiopian_and_Ancient_Books_Expansion_v1.pdf", "ancient",
     {7: "ancient", 13: "ancient", 21: "ancient", 30: "ancient",
      38: "ancient", 48: "ancient", 55: "ancient"}),
    ("Dream_Vibe_Guided_Dream_Journal_v1.pdf", "dream",
     {2: "dream", 11: "dream", 18: "dream", 25: "dream", 34: "dream"}),
    ("Read_the_Energy_Tarot_Oracle_Spiritual_Practice_Journal_v1.pdf", "tarot",
     {2: "tarot", 11: "tarot", 18: "tarot", 25: "tarot", 46: "tarot"}),
    ("Reading_Vibe_Book_Lovers_Library_Journal_v1.pdf", "reading",
     {11: "reading", 21: "reading", 32: "reading", 49: "reading",
      58: "reading", 66: "reading", 75: "reading"}),
    ("Reading_Vibe_Reusable_Book_Reflection_Pack_v1.pdf", "reflection", {}),
]

# divider one-page pdfs were generated by rebuild_dividers.py into covers/dividers/
DIV_DIR = os.path.join(COVERS, "dividers")

import glob, re
def divider_pdf(template, page):
    cands = glob.glob(os.path.join(DIV_DIR, f"{template}-{page}-*.pdf"))
    # filenames: {template}-{pnum}-{kicker-slug}.pdf ; template may contain '-'? no.
    assert cands, f"missing divider {template} p{page}"
    return cands[0]

def one_page_pdf(png_path):
    img = Image.open(png_path).convert("RGB").resize((612, 792), Image.LANCZOS)
    out = png_path.replace(".png", "-page.pdf")
    img.save(out, "PDF", resolution=72.0)
    return out

for v1, cover_key, divmap in JOBS:
    src = os.path.join(BASE, v1)
    reader = PdfReader(src)
    writer = PdfWriter()
    writer.clone_document_from_reader(reader)

    # replacements: (page_num, one_page_pdf) — cover is page 1
    repl = {1: one_page_pdf(os.path.join(COVERS, f"cover-{cover_key}-final.png"))}
    for pnum, tmpl in divmap.items():
        repl[pnum] = divider_pdf(tmpl, pnum)

    for pnum in sorted(repl, reverse=True):
        one = PdfReader(repl[pnum])
        writer.merge(position=pnum - 1, fileobj=one)
        del writer.pages[pnum]  # remove the old page (now shifted right)

    out = os.path.join(BASE, v1.replace("_v1.pdf", "_v2.pdf"))
    with open(out, "wb") as f:
        writer.write(out)
    chk = PdfReader(out)
    nf = len(chk.get_fields() or {})
    n1 = len(reader.get_fields() or {})
    print(f"{v1}: pages {len(reader.pages)}->{len(chk.pages)}, fields {n1}->{nf}, {len(repl)} pages replaced")
